#!/usr/bin/env bash
# Set up gsplat with a CUDA toolchain that matches the torch build.
#
#   ./scripts/setup_gsplat.sh
#
# Why this is needed: gsplat JIT-compiles its CUDA kernels through torch's
# cpp_extension, which requires an nvcc whose major version matches the torch
# build. This environment runs torch 2.9.1+cu129 (CUDA 12.9), but the system
# nvcc is 13.1 -- a mismatch. A matched CUDA 12.9 toolchain is installed into a
# dedicated conda env (cuda129), and a .pth file in the venv points every
# `.venv/bin/python` at it so gsplat builds/loads transparently.
#
# Idempotent: safe to re-run. Requires conda (anaconda3) and the project .venv.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

CONDA="${CONDA:-/home/pliam/anaconda3/condabin/conda}"
CUDA_ENV="cuda129"
CUDA_PREFIX="$($CONDA info --base)/envs/$CUDA_ENV"
SP=".venv/lib/python3.10/site-packages"

# 1. matched CUDA 12.9 build toolchain (nvcc + cudart headers/libs + cub/thrust)
if [ ! -x "$CUDA_PREFIX/bin/nvcc" ]; then
  echo "creating conda env '$CUDA_ENV' with CUDA 12.9 toolchain"
  "$CONDA" create -y -n "$CUDA_ENV" -c nvidia \
    "cuda-nvcc=12.9" "cuda-cudart-dev=12.9" "cuda-cccl=12.9"
else
  echo "conda env '$CUDA_ENV' already present"
fi
"$CUDA_PREFIX/bin/nvcc" --version | tail -2

# 2. gsplat (pure-python; CUDA kernels compile on first import)
echo "installing gsplat into .venv"
.venv/bin/pip install --no-input gsplat

# 3. point .venv/bin/python at the matched toolchain via a .pth import hook.
#    A venv sitecustomize.py is shadowed by the distro's /usr/lib sitecustomize,
#    but a .pth line beginning with `import` is always executed at startup. Both
#    files live under .venv (gitignored), so this script regenerates them.
echo "installing CUDA-env .pth hook into the venv"
cat > "$SP/_nuslam_cudaenv.py" <<PYEOF
"""Force this venv's interpreter to build/load gsplat with a CUDA 12.9 toolchain.

torch 2.9.1+cu129 needs a 12.x nvcc; the system nvcc is 13.1. A matched toolchain
lives in the conda env 'cuda129'. CUDA_HOME is forced to it (set
NUSLAM_KEEP_CUDA_HOME=1 to opt out). Regenerated by scripts/setup_gsplat.sh.
"""
import os
from pathlib import Path

_CUDA_HOME = Path("$CUDA_PREFIX")
_TARGETS = _CUDA_HOME / "targets" / "x86_64-linux"


def _prepend(var, value):
    parts = os.environ.get(var, "").split(os.pathsep)
    parts = [p for p in parts if p]
    if value not in parts:
        os.environ[var] = os.pathsep.join([value, *parts]) if parts else value


if (_CUDA_HOME / "bin" / "nvcc").is_file() and not os.environ.get("NUSLAM_KEEP_CUDA_HOME"):
    os.environ["CUDA_HOME"] = str(_CUDA_HOME)
    os.environ["CUDA_PATH"] = str(_CUDA_HOME)
    os.environ.setdefault("TORCH_CUDA_ARCH_LIST", "8.6")  # RTX 3080 Ti (Ampere)
    _prepend("PATH", str(_CUDA_HOME / "bin"))
    _prepend("CPATH", str(_TARGETS / "include"))
    _prepend("LIBRARY_PATH", str(_TARGETS / "lib"))
    _prepend("LIBRARY_PATH", str(_CUDA_HOME / "lib"))
PYEOF
printf 'import _nuslam_cudaenv\n' > "$SP/_nuslam_cudaenv.pth"

# 4. trigger the kernel build and verify it loads
echo "building gsplat CUDA kernels (first time ~2 min)"
.venv/bin/python -c "from gsplat.cuda._backend import _C; print('gsplat backend OK:', _C is not None)"

echo
echo "done. gsplat is ready; import it from .venv/bin/python."
